---
title: '123'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
分析的網頁

```{r}
library(httr)
library(rvest)
html_li <- "https://www.urcosme.com/tags/36/ranking"
ranking_cosmetic <- read_html(html_li)
```

抓產品名
```{r}
product_list <- ranking_cosmetic %>% 
  html_nodes(".single-dot") %>% 
  html_text()

product_list
product_list_new <- c()
for (i in 1:length(product_list)) {
  if (i %% 2 == 1) {
    product_list_new <- c(product_list_new, product_list[i])
  }
}
length(product_list_new)

product_list_new <- paste0(".single-dot" , product_list)
#View(product_list_new)
```

抓價錢
```{r}
money_list <- ranking_cosmetic %>% 
  html_nodes(".uc-tag-ranking-item:nth-child(11) span , .uc-tag-ranking-item:nth-child(9) span , .uc-tag-ranking-item:nth-child(5) span , .uc-tag-ranking-item:nth-child(2) span , span~ span+ span") %>%
  html_text()

money_list

length(money_list)
```

評價
```{r}
score_list <- ranking_cosmetic %>% 
  html_nodes(".urcosme-heart-full~ .product-score-text") %>%
  html_text()
as.numeric()
length(score_list)
score_list
```

抓圖
```{r}
poster_list <- ranking_cosmetic %>%
  html_nodes(".img-auto-center ") %>%
  html_attr("src")
poster_list
length(poster_list)
```

