---
title: "urcosme人氣專櫃品牌/人氣開架品牌"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
######################## library loaded ##############################
library(httr) # 爬蟲 GET()
library(rvest)
library(stringr) 
library(dplyr)
library(data.table)
library(DT)
library(RCurl)
library(tidyverse)
library(parallel)
library(plyr)
library(progress)

char_encode=URLencode(iconv('Maintenance_mask',to= 'UTF-8' ))
```

```{r}
######################## 1.Request: GET - 請求人氣專櫃品牌 ##############################]

# 人氣專櫃品牌的資料庫
 brand_counters_data<-data.frame()

#寫個迴圈，對固定網頁結構重複抓取
 brand_numbers <- c(38, 55, 508,14,68)

for (i in  brand_numbers) {
  
  # 這裡分各項名稱抓取資料--------
  num_brand <- i
  
  url_brand=sprintf("https://www.urcosme.com/brands/%s/main",num_brand)
  doc_brand<- GET(url_brand) %>% content(encoding = "utf8")
  
  #extract data wanted
  # 1.1 選定之品牌資訊 ####
  
  # 品牌名稱
  brand_name <- doc_brand %>% 
    html_nodes(".headline-title span:nth-child(1)") %>% 
    html_text()
  
  # 人關注品牌中
  focus<- doc_brand %>% 
    html_nodes('.focus-count')%>% 
    html_text()
  # 商品資料
  goods <- doc_brand %>% 
    html_nodes(".counting-item , .counting-item .text") %>% 
    html_text()
  
  
  # 使用心得
  feedback <- doc_brand %>% 
    html_nodes(".counting-item .text:nth-child(2)") %>% 
    html_text()
  
  
  #bought買過
  bought <- doc_brand %>% 
    html_nodes(".counting-item:nth-child(3) ") %>% 
    html_text()
  
  #love生火
  love <- doc_brand %>% 
    html_nodes(".counting-item:nth-child(4)") %>% 
    html_text()
  
  # make data frame
  brand_info <- data.frame( brand_name = ifelse(length( brand_name)==0,NA, brand_name), 
                              focus = ifelse(length(focus)==0,NA,focus), 
                            goods = ifelse(length( goods)==0,NA, goods),
                            feedback = ifelse(length( feedback)==0,NA, feedback),
                            bought = ifelse(length(bought)==0,NA, bought),
                            love = ifelse(length(love)==0,NA, love))
  
  
  #把此次資料輸到新的資料庫中
  brand_counters_data<-rbind(brand_counters_data,brand_info)  
}

#輸出結果 
View(brand_counters_data)
#輸出型態 str(brand_counters_data)
#取出特定欄位 brand_counters_data$focus

```


```{r}
######################## 2.Request: GET - 請求人氣開架品牌 ##############################]

# 人氣開架品牌的資料庫
Open_shelf_data<-data.frame()

#寫個迴圈，對固定網頁結構重複抓取
brand_numbers <- c(3488, 1058, 848,39,220)

for (i in  brand_numbers) {
  
  # 這裡分各項名稱抓取資料--------
  num_brand <- i
  url_brand=sprintf("https://www.urcosme.com/brands/%s/main",num_brand)
  doc_brand<- GET(url_brand) %>% content(encoding = "utf8")
  
  #extract data wanted
  # 1.1 選定之品牌資訊 ####
  
  # 品牌名稱
  brand_name <- doc_brand %>% 
    html_nodes(".headline-title span:nth-child(1)") %>% 
    html_text()
  
  # 人關注品牌中
  focus<- doc_brand %>% 
    html_nodes('.focus-count')%>% 
    html_text()
  # 商品資料
  goods <- doc_brand %>% 
    html_nodes(".counting-item , .counting-item .text") %>% 
    html_text()
  
  
  # 使用心得
  feedback <- doc_brand %>% 
    html_nodes(".counting-item .text:nth-child(2)") %>% 
    html_text()
  
  
  #bought買過
  bought <- doc_brand %>% 
    html_nodes(".counting-item:nth-child(3) ") %>% 
    html_text()
  
  #love生火
  love <- doc_brand %>% 
    html_nodes(".counting-item:nth-child(4)") %>% 
    html_text()
  
  # make data frame
  brand_info <- data.frame( brand_name = ifelse(length( brand_name)==0,NA, brand_name), 
                            focus = ifelse(length(focus)==0,NA,focus), 
                            goods = ifelse(length( goods)==0,NA, goods),
                            feedback = ifelse(length( feedback)==0,NA, feedback),
                            bought = ifelse(length(bought)==0,NA, bought),
                            love = ifelse(length(love)==0,NA, love))
  
  
  
  #把此次資料輸到新的資料庫中
  Open_shelf_data<-rbind(Open_shelf_data,brand_info)  
}

#輸出結果 
View(Open_shelf_data)
#輸出型態 str(Open_shelf_data)

```


