---
title: "R text Mining 京东区块链技术实践白皮书"
output: html_document
---
此份資料是 京东区块链技术实践白皮书
想了解這個白皮書的關鍵字


前置作業
```{r}
#清空所有記憶體
rm(list=ls(all.names = TRUE))
library(NLP)
library(tm) #文字探勘
library(jiebaRD)
library(jiebaR) #中文斷詞 
library(RColorBrewer)
library(wordcloud) #產生文字雲
```

放入資料
```{r}
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines, encoding="UTF-8")
docs <- Corpus(VectorSource(files))

```

文字清洗
```{r}
#移除可能有問題的符號
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
docs <- tm_map(docs, toSpace, "。")
docs <- tm_map(docs, toSpace, "，")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")
docs <- tm_map(docs, toSpace, "举举")
docs <- tm_map(docs, toSpace, "举")
docs <- tm_map(docs, toSpace, "对")
docs <- tm_map(docs, toSpace, "适")
docs <- tm_map(docs, toSpace, "上")
docs <- tm_map(docs, toSpace, "与")
docs <- tm_map(docs, toSpace, "容容")
docs <- tm_map(docs, toSpace, "之")
docs <- tm_map(docs, toSpace, "为")
docs <- tm_map(docs, toSpace, "一个")
docs <- tm_map(docs, toSpace, "久")
docs <- tm_map(docs, toSpace, "可")
docs <- tm_map(docs, toSpace, "及")
docs <- tm_map(docs, toSpace, "间")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "和")
docs <- tm_map(docs, toSpace, "容")

```

文字清洗
```{r}
#移除標點符號 (punctuation)
#移除數字 (digits)、空白 (white space)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)

```

進行中文斷詞：結巴字典
```{r}
#結巴字典
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))

library("jiebaR")
Sys.setlocale(category = "LC_ALL", locale = "cht")
```

畫出關鍵字詞 文字雲
```{r}
library(wordcloud)

par(family=("HeitiTC Light"))

mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
par(family=("Heiti TC Light"))

wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(5,0.5),min.freq=10,max.words=50,
          random.order=FALSE, random.color=TRUE, 
          rot.per=0, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)

```


